name: MacOS
on: 
  push:
    paths-ignore:
      - 'debian'
      - 'README.md'
      - 'LICENSE'
      - 'buildToVS2019.bat'
  pull_request:
    paths-ignore:
      - 'debian'
      - 'README.md'
      - 'LICENSE'
      - 'buildToVS2019.bat'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0]  # macos-10.15, macos-11.0
        qt_ver: [5.12.11]  # 参考: https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/mac_x64/desktop/qt5_5111
        qt_arch: [clang_64]
    env:
      targetName: PicShot
    steps:
      # - name: Cache Qt  # 使用缓存安装Qt模块
      #   id: cache-qt
      #   uses: actions/cache@v1  # not v2! 参见 https://github.com/jurplel/install-qt-action
      #   with:
      #     path: ../Qt
      #     key: ${{ runner.os }}-QtCache
      
      - name: Install Qt
        # if: steps.WindowsCacheQt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          # cached: ${{ steps.cache-qt.outputs.cache-hit }}
          set-env: true
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: pull 3rdparty code
        run: |
          cd ${{github.workspace}}
          git submodule init
          git submodule update

      # macos 11.0 默认环境变了,要指定
      - name: prepare env
        if: ${{ matrix.os == 'macos-11.0' }}
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools 

      - name: build macos
        run: |
          mkdir build
          cd build
          cmake ..
          make

          echo "-------------------------a1"
          pwd
          ls -al

          echo "-------------------------a2"
          cd bin
          ls -al


      - name: NameVersion
        id: NameVersion
        if: startsWith(github.event.ref, 'refs/tags/')
        shell: pwsh
        run: |
          $systemInfo="${{ env.targetOS }}-${{ matrix.msvc_arch }}"
          $productVersion="${{ github.ref }}".substring("refs/tags/v".length)
          $productName="${{ env.targetName }}-$productVersion-$systemInfo"

          echo "systemInfo=$systemInfo" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "productVersion=$productVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "productName=$productName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append


      # 打包
      - name: package
        id: package
        if: startsWith(github.event.ref, 'refs/tags/')
        shell: bash
        run: |
          # 拷贝依赖
          mkdir bin

          echo "-------------------------a0"
          pwd
          ls -al


          echo "-------------------------a1"
          pwd
          ls -al

          cp -r build/bin/${{ env.targetName }} bin

          echo "-------------------------a2"
          pwd
          ls -al

          echo "-------------------------a3"
          cd bin
          pwd
          ls -al
          
          macdeployqt ${{ env.targetName }} -dmg


          echo "-------------------------a4"
          pwd
          ls -al


          echo "-------------------------a5"
          cd ../
          pwd
          ls -al

          echo "-------------------------a6"
          cd bin
          ls -al
          pwd

      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.targetName }}.dmg
          asset_name: ${{ env.targetName }}_${{ matrix.os }}_${{ matrix.qt_ver }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
