Document: picshot
Title: Debian picshot Manual
Author: <insert document author here>
Abstract: This manual describes what picshot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/picshot/picshot.sgml.gz

Format: postscript
Files: /usr/share/doc/picshot/picshot.ps.gz

Format: text
Files: /usr/share/doc/picshot/picshot.text.gz

Format: HTML
Index: /usr/share/doc/picshot/html/index.html
Files: /usr/share/doc/picshot/html/*.html
